#https://medium.com/thefreshwrites/the-way-of-dockerize-a-spring-boot-and-mysql-application-with-docker-compose-de2fc03c6a42


version: "3.7"
services:
  api_device:
    build: .
    ports:
      - 8081:8081
    networks:
      - device-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/devices?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .device_db:/root/.device_db

  mysqldb:
    image: "mysql:8.0"
    networks:
      - device-net
    environment:
      MYSQL_DATABASE: devices
      MYSQL_ROOT_PASSWORD: Maria.12*ab
networks:
  device-net: