#https://medium.com/thefreshwrites/the-way-of-dockerize-a-spring-boot-and-mysql-application-with-docker-compose-de2fc03c6a42


version: "3.7"
services:
  api_user:
    build: .
    ports:
      - 8088:8088
    networks:
      - user-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ass3?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .user_db:/root/.user_db

  mysqldb:
    image: "mysql:8.0"
    networks:
      - user-net
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: Maria.12*ab
networks:
  user-net: