# https://medium.com/thefreshwrites/the-way-of-dockerize-a-spring-boot-and-mysql-application-with-docker-compose-de2fc03c6a42

version: "3.8"
services:
  app:
    build: .
    container_name: front
    ports:
      - "3000:3000"
    image: front
    command: npm start
