#https://medium.com/thefreshwrites/the-way-of-dockerize-a-spring-boot-and-mysql-application-with-docker-compose-de2fc03c6a42
# https://blog.christian-schou.dk/rabbitmq-deployment-with-docker-compose/

version: "3.7"
services:
  api_monitorizare:
    build: .
    ports:
      - 8083:8083
    networks:
      - senzor-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/monitorizare?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .senzor_db:/root/.senzor_db

  mysqldb:
    image: "mysql:8.0"
    networks:
      - senzor-net
    environment:
      MYSQL_DATABASE: monitorizare
      MYSQL_ROOT_PASSWORD: Maria.12*ab

networks:
  senzor-net: